### ISSUE TITLE
Unindent `Shift + Tab`

### ISSUE THREAD

**Issue by MadLittleMods** [kazzkiq/CodeFlask.js#11]
Add a keyboard shortcut to unindent(remove a level of indent, spaces or tabs).

`Shift + Tab` works well for this and lots of code editors use this keyboard shortcut.

**Comment by desertkun** [comment]
Looking for this as well! Will that happen in near future, or I'll have to do it myself?

**Comment by jeroenvisser101** [comment]
Fixed with #24

**Comment by kazzkiq** [comment]
#24 Solves this. Closing the issue.

**Comment by alexandrukis** [comment]
Can we reopen this? This is still not working in newer versions.
